# Generated by Django 5.2.1 on 2025-05-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_message', models.TextField()),
                ('ai_reply', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OCRScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('raw_text', models.TextField()),
                ('detected_medicines', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
